resource_group: "DenisSlyusarenko"
location: "Central US"
vnet_name: "myVNet"
subnet_name: "mySubnet"
nsg_name: "myNSG"
vm_name: "myVM"
vm_size: "Standard_B1s"
admin_username: "azureuser"
ssh_key_path: "~/.ssh/rsaazurekey_pub"
public_ip_name: "myPublicIP"
nic: "myNIC"
